### ISSUE TITLE
Does not update products for free

### ISSUE THREAD

**Issue by NachoVidalGolosinas** [code4business/freeproduct2#34]
### Preconditions
- Magento version: 2.4.2
- Module version: 1.0.0

### Settings / Sale Rules
1. Product free to subtotal > 10

### Steps to reproduce
1.  Add to cart 12€
2. Apply a discount coupon of 5€

### Expected result
1. I hope the gift is taken away

### Actual result
1. The gift is not taken away

**Comment by domeglic** [comment]
Thank you for the report. However this is how Magento sales rule work and it isn't easily possible to change. Subtotal doesn't include discounts, only grand total does which cannot be used in sales rules.

Gifts are added from a sales rule but since sales rules are processed during discount step, they can only use subtotal.
